### ISSUE TITLE
UI - Theme minimal

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/matrix-react-sdk-v4#12]

**Comment by estellecomment** [comment]
Logo suggestion for beta version :
![tchap-beta-logo](https://user-images.githubusercontent.com/911434/158826256-326ec205-bbb7-443a-a6e8-1ecea8c1b5a0.png)
Yes, this is art.

**Comment by estellecomment** [comment]
Still missing : 
 - [ ] colors of buttons and text in Login and Register pages

**Comment by celiacheff** [comment]
Closing this in favor of linked issue since it invlove more than just configuration
