### ISSUE TITLE
Technical choices : Hydrogen or element-web ?

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/matrix-react-sdk-v4#7]
Evaluate if hydrogen would be a better choice to fork from for tchap-web, compared to element-web.

https://hydrogen.element.io/

**Comment by estellecomment** [comment]
Missing features in Hydrogen : 
(Todo : assess, how important are they ?)

**Conversations**
 - No categories of conversations (DM vs room) : https://github.com/vector-im/hydrogen-web/issues/153 (the settings for public/private and encryption are present though)
 - No favoriting/starring conversations

**Creating conversations**
- you can create a DM from a person's profile, which you can reach by clicking on one of their messages. If you don't have a message to click, you can't create a DM. (no other way to create DM)
- can't add a person to a room ??

**Messages**
 - don't see which user posted a given reaction
 - no message edit
 - no permalink to message, share message
 - no threads
 - no read receipts (for each user, show how far they have read in the channel, by showing a mini-avatar on the side of the messages)

**Other**
- no registration of new account
- no spaces (we don’t use them in tchap yet) - the space is visualized as a channel, if you post in it nothing happens apparently
- no voice and video
- Notifications granularity : you can set them on or off, but there is no setting for each individual room
- no secure storage (key backup is present, but apparently we don't want to use it)

**Tchap stuff**
 - no externs
 - Antivirus ?

**Comment by estellecomment** [comment]
Element roadmap (all clients) : https://github.com/vector-im/roadmap/projects/1
 - Hydrogen is in "now", "ongoing R&D"
 - Threads is in "now" (so not done yet)
 
 Hydrogen roadmap : https://github.com/vector-im/hydrogen-web/projects/1
  - typescript conversion is ongoing. That is hell when we merge, filenames change.
  - are registration and adding user to channel in the roadmap ?
  
 Element-web, latest version (pre-release) : https://develop.element.io/
 Element-web roadmap : https://github.com/vector-im/element-web/projects/11
  - threads tickets : all of them are scheduled, none in backlog (https://github.com/vector-im/element-web/projects/11?card_filter_query=label%3Aa-threads) -> thread is not finished but it's in active dev

**Comment by estellecomment** [comment]
Overall it looks like Hydrogen is not meant to be a standalone client : it has no registration or adding users to channels, which are basic features. 
Maybe we can use it for embedding (a window for chatting with support in the landing page for instance, or just provide the option to embed tchap for other site developers)

Element is attractive because of some powerful features that are already there or coming up : voice and video (very common request from users), secure storage (which could help with loss of keys, a very common user problem).
And it allows us to keep most of the Tchap features that already exist (less confusing and irritating)

So I'm for forking element-web rather than hydrogen.

**Comment by jdauphant** [comment]
"No categories of conversations (DM vs room)" not sur it's :one: whatsapp don't have that. for me it's :two: 
"no registration of new account"  : We can have an standalone app for registration. We can also outsource registration to and identity management (that can be used by other administrations or product). i will give a :two:  on that for hydrogen.

I agreed with everything else and the choice to choose Element Web.

**Comment by estellecomment** [comment]
Talked with @celiacheff and he agrees too. Closing.
